services:
  anvil-uplink:
    # if something fails or the server is restarted, the container will restart
    restart: always 
    container_name: anvil-uplink
    image: anvil-uplink
    # FOLDERNAME = container path where host /home is mounted (e.g. app at /home/ubuntu/connect4app -> /FOLDERNAME/ubuntu/connect4app)
    volumes:
      - /home:/FOLDERNAME
    build: 
      # build the image from the Dockerfile in the current directory
      context: .
